CREATE TABLE [dbo].[VisitorLog](
	[VisitorLogId] [bigint] IDENTITY(1,1) NOT NULL,
	[VisitorLogDate] [date] NOT NULL,
	[StudentId] [bigint] NOT NULL,
 CONSTRAINT [PK_VisitorLog] PRIMARY KEY CLUSTERED 
(
	[VisitorLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO